// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// coachesDao is the data access object for the table coaches.
// You can define custom methods on it to extend its functionality as needed.
type coachesDao struct {
	*internal.CoachesDao
}

var (
	// Coaches is a globally accessible object for table coaches operations.
	Coaches = coachesDao{internal.NewCoachesDao()}
)

// Add your custom methods and functionality below.
