// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// containmentRepoDao is the data access object for the table containment_repo.
// You can define custom methods on it to extend its functionality as needed.
type containmentRepoDao struct {
	*internal.ContainmentRepoDao
}

var (
	// ContainmentRepo is a globally accessible object for table containment_repo operations.
	ContainmentRepo = containmentRepoDao{internal.NewContainmentRepoDao()}
)

// Add your custom methods and functionality below.
