// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// forumCommentsDao is the data access object for the table forum_comments.
// You can define custom methods on it to extend its functionality as needed.
type forumCommentsDao struct {
	*internal.ForumCommentsDao
}

var (
	// ForumComments is a globally accessible object for table forum_comments operations.
	ForumComments = forumCommentsDao{internal.NewForumCommentsDao()}
)

// Add your custom methods and functionality below.
