// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// forumSectionsDao is the data access object for the table forum_sections.
// You can define custom methods on it to extend its functionality as needed.
type forumSectionsDao struct {
	*internal.ForumSectionsDao
}

var (
	// ForumSections is a globally accessible object for table forum_sections operations.
	ForumSections = forumSectionsDao{internal.NewForumSectionsDao()}
)

// Add your custom methods and functionality below.
