// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// forumPostsDao is the data access object for the table forum_posts.
// You can define custom methods on it to extend its functionality as needed.
type forumPostsDao struct {
	*internal.ForumPostsDao
}

var (
	// ForumPosts is a globally accessible object for table forum_posts operations.
	ForumPosts = forumPostsDao{internal.NewForumPostsDao()}
)

// Add your custom methods and functionality below.
