// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// forumBoardsDao is the data access object for the table forum_boards.
// You can define custom methods on it to extend its functionality as needed.
type forumBoardsDao struct {
	*internal.ForumBoardsDao
}

var (
	// ForumBoards is a globally accessible object for table forum_boards operations.
	ForumBoards = forumBoardsDao{internal.NewForumBoardsDao()}
)

// Add your custom methods and functionality below.
