// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// groupClassEnrollmentsDao is the data access object for the table group_class_enrollments.
// You can define custom methods on it to extend its functionality as needed.
type groupClassEnrollmentsDao struct {
	*internal.GroupClassEnrollmentsDao
}

var (
	// GroupClassEnrollments is a globally accessible object for table group_class_enrollments operations.
	GroupClassEnrollments = groupClassEnrollmentsDao{internal.NewGroupClassEnrollmentsDao()}
)

// Add your custom methods and functionality below.
