// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// groupClassesDao is the data access object for the table group_classes.
// You can define custom methods on it to extend its functionality as needed.
type groupClassesDao struct {
	*internal.GroupClassesDao
}

var (
	// GroupClasses is a globally accessible object for table group_classes operations.
	GroupClasses = groupClassesDao{internal.NewGroupClassesDao()}
)

// Add your custom methods and functionality below.
