// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// roleCardsDao is the data access object for the table role_cards.
// You can define custom methods on it to extend its functionality as needed.
type roleCardsDao struct {
	*internal.RoleCardsDao
}

var (
	// RoleCards is a globally accessible object for table role_cards operations.
	RoleCards = roleCardsDao{internal.NewRoleCardsDao()}
)

// Add your custom methods and functionality below.
