// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// trpgRoomDao is the data access object for the table trpg_room.
// You can define custom methods on it to extend its functionality as needed.
type trpgRoomDao struct {
	*internal.TrpgRoomDao
}

var (
	// TrpgRoom is a globally accessible object for table trpg_room operations.
	TrpgRoom = trpgRoomDao{internal.NewTrpgRoomDao()}
)

// Add your custom methods and functionality below.
