// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"TrangleAgent/internal/dao/internal"
)

// workoutLogsDao is the data access object for the table workout_logs.
// You can define custom methods on it to extend its functionality as needed.
type workoutLogsDao struct {
	*internal.WorkoutLogsDao
}

var (
	// WorkoutLogs is a globally accessible object for table workout_logs operations.
	WorkoutLogs = workoutLogsDao{internal.NewWorkoutLogsDao()}
)

// Add your custom methods and functionality below.
